package com.mobileprism.fishing.model.entity.solunar

data class Solunar(
    val dayRating: Int,
    val hourlyRating: HourlyRating = HourlyRating(),
    val major1Start: String,
    val major1StartDec: Double,
    val major1Stop: String,
    val major1StopDec: Double,
    val major2Start: String,
    val major2StartDec: Double,
    val major2Stop: String,
    val major2StopDec: Double,
    val minor1Start: String,
    val minor1StartDec: Double,
    val minor1Stop: String,
    val minor1StopDec: Double,
    val minor2Start: String,
    val minor2StartDec: Double,
    val minor2Stop: String,
    val minor2StopDec: Double,
    val moonIllumination: Double,
    val moonPhase: String,
    val moonRise: String,
    val moonRiseDec: Double,
    val moonSet: String,
    val moonSetDec: Double,
    val moonTransit: String,
    val moonTransitDec: Double,
    val moonUnder: String,
    val moonUnderDec: Double,
    val sunRise: String,
    val sunRiseDec: Double,
    val sunSet: String,
    val sunSetDec: Double,
    val sunTransit: String,
    val sunTransitDec: Double
)